# action.yml
name: register to gym class
description: |
  Hay que pasarle las siguientes env vars:
    USER
    PASS
    GYM_PROGRAM_ID
    GYM_CLASS_ID
    DAYS_TO_ADD (opcional)
# inputs:
#   username:
#     description: Username to log in
#     required: true
#   password:
#     description: Password to log in
#     required: true
#   gym_program_id:
#     description: El id del programa de gimnasio en la url
#   gym_class_id:
#     description: 'El nombre en el selector de la clase. Ejemplo: 14:00 Sala 2'
#   days_to_add:
#     description: El número de días a añadir. Por defecto 7.
#     default: "7"

runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
  #   - ${{ inputs.username }}
  #   - ${{ inputs.password }}
  #   - ${{ inputs.gym_program_id }}
  #   - ${{ inputs.gym_class_id }}
  #   - ${{ inputs.days_to_add }}
