name: Register to gym class

on:
  workflow_dispatch:

jobs:
  register-hornero:
    runs-on: ubuntu-latest
    environment: hornero

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run script register to class
        run: docker run ghcr.io/mhornero91/crossfit-automation:main
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          GYM_PROGRAM_ID: 582c3718697e160007a02331
          GYM_CLASS_ID: 14:00 Sala 2
          DAYS_TO_ADD: "1"
