name: Register Hornero to gym class

on:
  workflow_dispatch:
  schedule:
    - cron: '15 19 * * *'

jobs:
  register-hornero:
    runs-on: ubuntu-latest
    environment: hornero

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run script register to class
        # If the env has not value, docker get it from the host: https://vsupalov.com/docker-environment-variables-from-host/#passing-environment-variable-values
        run: |
          docker run \
            -e USER \
            -e PASS \
            -e GYM_PROGRAM_ID \
            -e GYM_CLASS_SELECTOR \
            -e DAYS_TO_ADD \
            -e TELEGRAM_TOKEN \
          ghcr.io/mhornero91/crossfit-automation:main
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          GYM_PROGRAM_ID: 582c3718697e160007a02331
          GYM_CLASS_SELECTOR: 16:00
          DAYS_TO_ADD: 6
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
