name: Register to gym class

on:
  workflow_dispatch:
  # TODO: remove push
  push:

jobs:
  register-hornero:
    runs-on: ubuntu-latest
    environment: hornero

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # TODO: Move to docker
      # - name: Run script register to class
      #   # If the env has not value, docker get it from the host: https://vsupalov.com/docker-environment-variables-from-host/#passing-environment-variable-values
      #   run: |
      #     docker run \
      #       -e USER \
      #       -e PASS \
      #       -e GYM_PROGRAM_ID \
      #       -e GYM_CLASS_ID \
      #       -e DAYS_TO_ADD \
      #     ghcr.io/mhornero91/crossfit-automation:main
      #   env:
      #     USER: ${{ secrets.USER }}
      #     PASS: ${{ secrets.PASS }}
      #     GYM_PROGRAM_ID: 582c3718697e160007a02331
      #     GYM_CLASS_ID: 14:00 Sala 2
      #     DAYS_TO_ADD: "1"
      - name: Run script register to class
        # If the env has not value, docker get it from the host: https://vsupalov.com/docker-environment-variables-from-host/#passing-environment-variable-values
        run: |
          npm install && npm install && npx playwright install chromium
          npm start
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          GYM_PROGRAM_ID: 582c3718697e160007a02331
          GYM_CLASS_ID: 14:00 Sala 2
          DAYS_TO_ADD: "1"
